version: "3.9"

services:
    lavalink:
        container_name: lavalink
        image: fredboat/lavalink:latest
        ports:
            - "3333:3333"
        expose:
            - "3333"
        restart: unless-stopped
        volumes:
            - ./application.yml:/opt/Lavalink/application.yml
